### ISSUE TITLE
Hang system broken

### ISSUE THREAD

**Issue by sunilkr** [abhishekkr/n00bRAT#1]
cat /dev/port does not hang Ubuntu10.04LTS now.

**Comment by abhishekkr** [comment]
hey, thanks for the info, I haven't checked 'Hang' feature after
'initial' submission... I'll change it to a 'sudo-ed fork-bomb' that
shall be effective till now I think.

Though, my first task in that list is correcting the encode-decode
part in JS so that demand of secure communication could be completed.
Still... this change should be quick.
